### ISSUE TITLE
Remove languages

### ISSUE THREAD

**Issue by rappen** [BenediktBergmann/WordPress-Auto-MS-CreatorId#1]
Remove all `/en-us/` etc in the URL,so clickers can get it in their language.

**Comment by BenediktBergmann** [comment]
I just pushed a new version where this should be handled.

**Comment by rappen** [comment]
It is **always** removing the first part och the path. If I add a link without the locale (/sw-se/) it breaks this link.

My link:
`https://learn.microsoft.com/power-apps/maker/data-platform/solutions-overview`

Result:
`https://learn.microsoft.com/en-us/maker/data-platform/solutions-overview?WT.mc_id=BA-MVP-5002475`
(missing `/power-apps/`)

**Comment by BenediktBergmann** [comment]
The new version I just pushed should fix that
